# Analysis Objectives
- Delivery time distribution
- Quantity per days
- Rating distribution
- Most common cities
- Most common items
- Most common payment methods
- Most common restuerants

In [3]:
import pandas as pd
data = pd.read_csv("data/Food_Delivery.csv")
data.head()

,order_id,customer_id,restaurant,city,order_date,delivery_time_minutes,item,quantity,price,discount,payment_method,rating
0,1,1102,Kebab House,alex,2024-01-01 00:00:00,40.0,Kebab,4,265,13,Wallet,1.0
1,2,1435,Sushi World,alex,2024-01-01 01:00:00,30.0,Pasta,2,241,5,Card,3.0
2,3,1860,Burger Town,Cairo,2024-01-01 02:00:00,NaN,Pasta,3,240,13,Wallet,2.0
3,4,1270,Sushi World,cairo,2024-01-01 03:00:00,43.0,Kebab,3,269,16,Wallet,2.0
4,5,1106,Burger Town,Cairo,2024-01-01 04:00:00,12.0,Pizza,1,129,17,Cash,2.0

# Dataset Understanding

In [4]:
data.shape

(2050, 12)

In [8]:
data.ndim

2

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               2050 non-null   int64
 1   customer_id            2050 non-null   int64
 2   restaurant             2050 non-null   str
 3   city                   1947 non-null   str
 4   order_date             2050 non-null   str
 5   delivery_time_minutes  1943 non-null   float64
 6   item                   2050 non-null   str
 7   quantity               2050 non-null   int64
 8   price                  2050 non-null   int64
 9   discount               2050 non-null   int64
 10  payment_method         2050 non-null   str
 11  rating                 1945 non-null   float64
dtypes: float64(2), int64(5), str(5)
memory usage: 192.3 KB

In [9]:
data.columns

Index(['order_id', 'customer_id', 'restaurant', 'city', 'order_date',
       'delivery_time_minutes', 'item', 'quantity', 'price', 'discount',
       'payment_method', 'rating'],
      dtype='str')

In [10]:
data.dtypes

order_id                   int64
customer_id                int64
restaurant                   str
city                         str
order_date                   str
delivery_time_minutes    float64
item                         str
quantity                   int64
price                      int64
discount                   int64
payment_method               str
rating                   float64
dtype: object

In [16]:
data.describe()

,order_id,customer_id,delivery_time_minutes,quantity,price,discount,rating
count,2050.000000,2050.000000,1943.000000,2050.000000,2050.000000,2050.000000,1945.000000
mean,1000.057073,1499.454634,35.249614,2.650244,172.146829,14.497561,2.972751
std,577.001897,294.397792,18.997235,2.402641,71.659016,8.451408,1.412677
min,1.000000,1000.000000,-3.000000,1.000000,50.000000,0.000000,1.000000
25%,501.250000,1232.000000,26.000000,1.000000,111.000000,7.000000,2.000000
50%,1001.500000,1505.000000,35.000000,3.000000,170.000000,15.000000,3.000000
75%,1497.750000,1761.000000,43.000000,4.000000,233.750000,22.000000,4.000000
max,2000.000000,1998.000000,292.000000,41.000000,299.000000,29.000000,5.000000

In [14]:
data.sample(5)

,order_id,customer_id,restaurant,city,order_date,delivery_time_minutes,item,quantity,price,discount,payment_method,rating
1909,1910,1481,Pizza Hub,Alex,2024-03-20 13:00:00,50.0,Burger,3,57,22,Wallet,2.0
873,874,1444,Kebab House,alex,2024-02-06 09:00:00,35.0,Pasta,3,227,19,Wallet,5.0
418,419,1397,Pasta Point,Alex,2024-01-18 10:00:00,38.0,Pizza,2,127,8,Card,1.0
121,122,1791,Kebab House,Alex,2024-01-06 01:00:00,47.0,Sushi,3,242,6,Wallet,2.0
1753,1754,1672,Pizza Hub,Giza,2024-03-14 01:00:00,22.0,Kebab,4,214,12,Card,1.0

- Dataset dimentions => 2
#
- Numerical columns => order_id/customer_id/delivery_time_minutes/quantity/price/discount/rating
- Categorical columns => restaurant/city/order_date/item/payment_method
#
- Some columns data types may require to be changed
- There are some invalid entries that may require cleaning later